website:
  title: List of movies
  repo: https://github.com/cigolpl/movies
  layout: 
    name: table
    columns: 
      - image
      - name
      - tags
search:
  aggregations:
    tags: 
      size: 15
      title: Tags
    actors: 
      size: 10
      title: Actors
data:
  type: url
  url: https://storage.googleapis.com/imdb-list/imdb.json
